name: IvanaTaylor
favicon: null
layout_spectrum: 0.22304464736953378
typography_spectrum: 0.7559154250193387
title: Ivana S. Taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9670564953703433
  lightness: 0.36479893140494823
  saturation: 0.234123075613752
  rhythmicContrast: 0.9566809593234211
purpose: []
